name: Workflow Env Example
on: workflow_dispatch

env:
  APP_NAME: Test_App_Name
  OTHER_APP_NAME: Therizino For the Win
  DEPLOY_ENV: production
  GREETING: "Hello from workflow-level env!"

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print all environment variables
        run: |
          echo "App Name: $APP_NAME"
          echo "Deploy environment: " ${{ env.OTHER_APP_NAME }}
          echo "Message: $GREETING"
  # connection:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - name: Print All env variables
  #       run: |
  #           echo "App Name:" ${{ variables.APP_NAME }}