name: issue-comment
on:
  issue_comment:
    types: [created]


jobs:
  issue-pr-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Issues Number: '${{ toJson(github.event) }}'"