name: issue-workflow-hmw
on:
  issues:
    types: [created]


jobs:
  issue-job-homework:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: |
          echo "Issues Number: '${{ github.event.issue.number }}'"
          echo "Comments: ${{ github.event}}" 