name: pull_request-workflow
on: 
  pull_request:
    types: [opened]

jobs:
  pull-request-job:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        run: echo "This is a pull request workflow"
      - name: step 2
        run: |
          echo '${{ toJson(github) }}'
          echo "Running multiple commands"