name: CI - Gradle Tests

on:
  workflow_dispatch
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checksout the repo to have it locally
      - name: Checkout source
        uses: actions/checkout@v4
        # Sets up java 17 on the local ubuntu latest
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

# Grabs the gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-cache-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-cache-

# Makes gradle executable within the project
      - name: Make Gradle executable
        run: chmod +x ./SpringReact/gradlew

# Runs the test
      - name: Run tests
        working-directory: SpringReact
        run: ./gradlew clean test --no-daemon

# Uploads the artifact of the html within reports inside the project
      - name: Upload test reports (HTML)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-html-report
          path: SpringReact/build/reports/tests/test
